### ISSUE TITLE
Remove long code duplication

### ISSUE THREAD

**Issue by HknLof** [DataCater/datacater#119]
In our `runner.py` we now have two function, which almost do the same thing and have a roughly 100 lines duplications. Let's put some effort into cleaning this up in the coming weeks.

Reference:
First Block
https://github.com/DataCater/datacater/blob/main/python-runner/runner.py#L87

Second Block
https://github.com/DataCater/datacater/blob/main/python-runner/runner.py#L209

**Comment by flippingbits** [comment]
@HknLof and I had a look at this issue in a call. Removing duplicates looks rather complicated. We ignore it for now.
