### ISSUE TITLE
Make Kubernetes Deployment Configuration configurable

### ISSUE THREAD

**Issue by ChrisRousey** [DataCater/datacater#15]
As of now, we are using a static K8 configuration for things such are resources (replicas, memory, cpu...). 
The Static configurations can be found in the `Deployment.StaticConfig`-class.
The Configurations are being set while creating a deployment in the `Deployment.K8Deployment.create`-method

The goal of this ticket is to use a dynamic config when starting a deployment.
For this, we should: 
- have standard values in the case that user doesn't explicitly set them (we can use the current static values as a default).
- create a new class `DeploymentSpec` should be introduced to hold the configuration
  * An object of this class can optionally be given to put/post deployment
- We should use the k8 naming for the configurations i.e. `replicas`, `resources.requests.memory`, `resources.limits.memory`...

**Comment by HknLof** [comment]
Setting Replicas is still open.
