### ISSUE TITLE
Remote Development with Quarkus

### ISSUE THREAD

**Issue by ChrisRousey** [DataCater/datacater#153]

**Comment by ChrisRousey** [comment]
Add folowing dependencies:

1. `quarkusDev 'io.quarkus:quarkus-minikube'`
2. `quarkusDev 'io.quarkus:quarkus-container-image-docker'`

change to minikube container registry
`eval $(minikube -p minikube docker-env)`

build application with gradle, it will start in minikube
`../gradlew build -x test -Dquarkus.kubernetes.deploy=true`

**Comment by ChrisRousey** [comment]
notes:

- what should networking path be? needs to be set with variable `quarkus.live-reload.url=http://my.cluster.host.com:8080`
- need to add arg to start in dev mode

**Comment by HknLof** [comment]
So it works, but the dev console is not available or it can not reload classes into the jar?

**Comment by ChrisRousey** [comment]
@HknLof it's not the probes causing the problems, but our filters and transforms paths are causing our app to fail when running remote.

**Comment by HknLof** [comment]
So we need to account for mounting the folder by adjusting the Dockerfile?

**Comment by ChrisRousey** [comment]
That's my guess. We could have a look together on monday if you'd like.

**Comment by HknLof** [comment]
Currently, we are loading the images with `load-image-k8s`, that seems to be sufficient at this point. Closing!
