### ISSUE TITLE
Wrong amount of records displayed in pipeline designer

### ISSUE THREAD

**Issue by olis1996** [DataCater/datacater#155]
**Description:** Inside the pipeline designer the wrong number of records is displayed.

**Steps to reproduce:**
1.) Load 200 records into the kafka topic.
2.) Go to the pipeline designer.
3.) Per default 100 sample records are being displayed.
4.) Open sidebar and set sample size to 200.
5.) Save settings and close sidebar.
=> 186 records are being displayed

![image](https://user-images.githubusercontent.com/117189521/217589868-c6aaf245-0555-46ad-9c78-1551e7fd5608.png)

6.) Set sample size to anything >= 241
=> 200 records are being displayed correctly

![image](https://user-images.githubusercontent.com/117189521/217590119-1b74be4b-1d49-4e3a-a8d4-2f2d95e52f96.png)
![image](https://user-images.githubusercontent.com/117189521/217590246-9ddf886b-6cb4-450a-9adc-f0bd4fd5ca71.png)

**Comment by flippingbits** [comment]
This might be related to the implementation of the [KafkaStreamsAdmin.inspect](https://github.com/DataCater/datacater/blob/main/platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java#L178) method and is certainly confusing for users.

Are you using a Kafka topic with multiple partitions, where some partitions contain no or only a few records?

**Comment by olis1996** [comment]
There are 3 partitions, which might happen to contain very different amounts of records

**Comment by flippingbits** [comment]
When we retrieve `n` sample records from a topic with `m` partitions,  we currently try to consume `n/m` records from each partition.

If any of the partitions holds less than `n/m` records, this might lead to the unexpected situation where the `/streams/:uuid/inspect` endpoint returns less records than requested, even if the topic holds >= `n` records across all partitions.

I propose to change the sampling approach such that we always return `n` records if the topic holds >= `n` records across all partitions, regardless of any skew.

**Comment by HknLof** [comment]
@olis1996 For now, it might be useful to create a topic with a single partition to manually test your data-generator.

**Comment by ChrisRousey** [comment]
We will change the [Stream/Inspect](https://github.com/DataCater/datacater/blob/main/platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java#L172-L233) to offer two modes of operation, which can be switched with a variable flag

The first mode will be the new default and will be to retrieve the messages top-down. We will try and get all messages from the first partition, if that set doesn't contain 'x', we will continue with the next partition etc.

The second mode will be the current implementation where we try and evenly spread the amount retrieved accross all partitions.

**Comment by ChrisRousey** [comment]
This has been fixedwith PR #158
