### ISSUE TITLE
Add user guide: How to filter out records

### ISSUE THREAD

**Issue by flippingbits** [DataCater/datacater#163]
Add a new user guide to our [documentation](https://docs.datacater.io) that explains how to filter out a record with a pipeline.

**Comment by flippingbits** [comment]
@HknLof @olis1996 @ChrisRousey I submitted a draft of the guide for review in Gitbook.

**Comment by ChrisRousey** [comment]
Looks good to me, i left one question in the comments 👍🏼

**Comment by flippingbits** [comment]
Thank you very much! Guide is [now online](https://docs.datacater.io/using-datacater-open-core/filtering-out-records).
