### ISSUE TITLE
Support YAML in API endpoints

### ISSUE THREAD

**Issue by flippingbits** [DataCater/datacater#177]
At the moment, our API endpoints speak only JSON.

We should introduce the support for YAML because a lot of our users prefer YAML over JSON for defining, for instance, pipeline specifications.

We should not break the current behavior and stick to JSON as the default data format. However, users should be able to use YAML as the data format for their API calls by setting the request headers `Content-Type` and/or `Accept` to `application/x-yaml`.

**Comment by HknLof** [comment]
As of Quarkus 2.16.5.Final it should be possible to use the `jackson-jaxrs-yaml-provider`, which automatically uses the right Serde format.

https://github.com/quarkusio/quarkus/issues/31818

**Comment by flippingbits** [comment]
Fixed by #210
