### ISSUE TITLE
Implement integration tests for kubernetes

### ISSUE THREAD

**Issue by ChrisRousey** [DataCater/datacater#193]
As of now, we have unit tests for testing application functionalities. There are some functionalities, that can't be tested through unit tests, since they require a actual underlying kubernetes instance. These tests should:

- Test the deployment metrics endpoints
- Test the deployment health endpoints
- Test the deployment logs endpooints

**Comment by HknLof** [comment]
Usage of Quarkus DevServices for non-mockable calls to Kubernetes as mentioned in the PR #178 . E2E Tests with Kubernetes / minikube will be a separate issue.

**Comment by HknLof** [comment]
Thanks :)

Can we replace `@Ignore` with `@Disable`?
