### ISSUE TITLE
Frontend: Use Hyperlink `<a>` when appropriate

### ISSUE THREAD

**Issue by HknLof** [DataCater/datacater#196]
We use `<a href="#">` a lot in our codebase. This is no functional issue, but we can be cleaner with hyperlink tag usage, by reducing the use to actually navigate to specific places in our UI.

When no navigation is needed it might make sense to replace hyperlink tags with `<Button>` elements.

**Comment by HknLof** [comment]
Discuss, whether refactoring this is worth the ROI.

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me ?

**Comment by flippingbits** [comment]
Hi @sumitshinde-84 - I assigned you to this issue. Please let us know if you need any help when working on it. We look forward to your PR! 🚀

**Comment by sumitshinde-84** [comment]
Thank you so much for assigning this issue to me , I will give my best .

**Comment by flippingbits** [comment]
Thanks for contributing! Feel free to join our [Slack](https://join.slack.com/t/datacater/shared_invite/zt-17cga6jg3-rGdgQZU6iX~mJGC8j~UNlw) if you have any questions.

**Comment by sumitshinde-84** [comment]
@ChrisRousey Sorry  I was busy but now I am gonna work on it.

**Comment by ChrisRousey** [comment]
@sumitshinde-84 it's fine, do it at your own pace! I just wanted to make sure you get the help and resources you need in case you have any problems or need help setting things up 🙂
