### ISSUE TITLE
Come up with reasonable default resource requests for pipelines

### ISSUE THREAD

**Issue by ChrisRousey** [DataCater/datacater#20]
As of now, we configure each pipeline deployment to use 1.5GB of memory.

With this issue, we should evaluate how much memory should be allocated to each deployment as a standard.

**Comment by flippingbits** [comment]
From my experience, we can reduce the requested memory to 300MB for non-native pipelines, and might be able to further reduce the requests for native pipelines.

WDYT, @ChrisRousey @HknLof
