### ISSUE TITLE
Allow to overwrite stream config of deployment in UI

### ISSUE THREAD

**Issue by flippingbits** [DataCater/datacater#49]
By default, a deployment gets the stream-in and stream-out config from the associated pipeline object.

Additionally, one can also provide inline stream configs in the deployment specs, which overwrites the stream configs of the pipeline object.

We should make the latter one available in the UI.

**Comment by ChrisRousey** [comment]
@HknLof @flippingbits 
Is this still relevant now since we have the configs rersource? It is also possible to define a stream-in and stream-out uuid inside a deployment definition to overwrite them.

**Comment by flippingbits** [comment]
I agree. I think it is fine to close it for now.
