### ISSUE TITLE
Stateful set python-runner does not get cleaned up

### ISSUE THREAD

**Issue by flippingbits** [DataCater/datacater#67]
When uninstalling DataCater via `kubectl delete -f ...`, all DataCater resources except the `python-runner` stateful set get removed.

We should fix this to leave a clean Kubernetes namespace after removing DataCater.

**Comment by HknLof** [comment]
Is there a Quarkus / Kubernetes event, that we might use for this? Otherwise, let us remove the initiation of our `python-runner` StatefulSet from the application and build it into helm.

**Comment by flippingbits** [comment]
This should be fixed now, closing the issue.
